# Generated by Django 5.2 on 2025-07-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblistings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
