# Generated by Django 5.2.1 on 2026-01-04 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_joblistings_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(default={}, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='parsed_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='applicant_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
