# Generated by Django 5.2.1 on 2026-01-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_applicant_first_name_applicant_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='meeting_type',
            field=models.CharField(default='Technical Interview', max_length=50),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
