# Generated by Django 5.2.1 on 2026-01-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_interviewschedule_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
